definitions:
  handler.CreateOrderRequest:
    properties:
      amount:
        type: number
    type: object
  handler.Error:
    properties:
      message:
        type: string
    type: object
  handler.Order:
    properties:
      amount:
        type: number
      id:
        type: string
      status:
        type: string
      user_id:
        type: string
    type: object
  handler.PaymentStruct:
    properties:
      amount:
        description: Для запросов пополнения
        type: number
      balance:
        description: Для ответов с балансом
        type: number
      message:
        description: Для ошибок
        type: string
      success:
        description: Статус операции
        type: boolean
    type: object
info:
  contact: {}
paths:
  /order/{user_id}:
    post:
      consumes:
      - application/json
      description: Create new order
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Order data
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.Order'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Create order
      tags:
      - orders
  /order/{user_id}/{order_id}:
    get:
      description: Get status for specific order
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Order ID
        in: path
        name: order_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Order'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get order status
      tags:
      - orders
  /orders/{user_id}:
    get:
      description: Get all orders for user
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/handler.Order'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.Error'
      summary: Get user orders
      tags:
      - orders
  /payment/{user_id}:
    get:
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PaymentStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.PaymentStruct'
      summary: Получить баланс
      tags:
      - payment
    post:
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/handler.PaymentStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.PaymentStruct'
      summary: Создать платежный аккаунт
      tags:
      - payment
  /payment/{user_id}/deposit:
    put:
      parameters:
      - description: ID пользователя
        in: path
        name: user_id
        required: true
        type: string
      - description: Сумма пополнения
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/handler.PaymentStruct'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.PaymentStruct'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handler.PaymentStruct'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handler.PaymentStruct'
      summary: Пополнить баланс
      tags:
      - payment
swagger: "2.0"
